// SUSPENDED: Spotify API access paused. See docs/features/SPOTIFY_INTEGRATION.md

import { type NextRequest, NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import lineup from '@/data/lineup.json';
import { FESTIVAL } from '@/config/festival-engine';
import type { LineupItem } from '@/types';

interface SpotifyTrack {
  uri: string;
}

function getSpotifyId(url: string | null | undefined): string | null {
    if (!url) return null;
    const match = url.match(/artist\/([a-zA-Z0-9]+)/);
    return match ? match[1] : null;
}

export async function POST(request: NextRequest) {
    const cookieStore = await cookies();
    const token = cookieStore.get('spotify_access_token');
    if (!token?.value) {
        return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
    }

    const body = await request.json() as { artistIds?: string[] };
    const artistIds = body.artistIds;
    if (!Array.isArray(artistIds) || artistIds.length === 0) {
        return NextResponse.json({ error: 'No artists provided' }, { status: 400 });
    }

    const accessToken = token.value;
    const headers = {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
    };

    try {
        // 1. Get Spotify user ID
        const meRes = await fetch('https://api.spotify.com/v1/me', { headers });
        if (meRes.status === 401) return NextResponse.json({ error: 'Token expired' }, { status: 401 });
        if (!meRes.ok) throw new Error('Failed to fetch user profile');
        const { id: userId } = await meRes.json() as { id: string };

        // 2. Build festival artist ID → Spotify artist ID map
        const lineupMap = new Map<string, string>();
        (lineup as LineupItem[]).forEach((a) => {
            const sid = getSpotifyId(a.socials?.spotify);
            if (sid) lineupMap.set(a.id, sid);
        });

        // 3. Get top 3 tracks per matched artist
        const trackUris: string[] = [];
        await Promise.all(
            artistIds.map(async (artistId) => {
                const spotifyArtistId = lineupMap.get(artistId);
                if (!spotifyArtistId) return;
                const tracksRes = await fetch(
                    `https://api.spotify.com/v1/artists/${spotifyArtistId}/top-tracks?market=${FESTIVAL.location.countryCode}`,
                    { headers }
                );
                if (!tracksRes.ok) return;
                const { tracks } = await tracksRes.json() as { tracks: SpotifyTrack[] };
                tracks.slice(0, 3).forEach((t) => trackUris.push(t.uri));
            })
        );

        if (trackUris.length === 0) {
            return NextResponse.json({ error: 'No tracks found for selected artists' }, { status: 400 });
        }

        // 4. Create playlist
        const createRes = await fetch(`https://api.spotify.com/v1/users/${userId}/playlists`, {
            method: 'POST',
            headers,
            body: JSON.stringify({
                name: `My ${FESTIVAL.name} ${FESTIVAL.dates.year} Lineup`,
                description: `Generated by ${FESTIVAL.appName} — your personal festival playlist.`,
                public: false,
            }),
        });
        if (createRes.status === 403) {
            return NextResponse.json({ error: 'scope_missing' }, { status: 403 });
        }
        if (!createRes.ok) throw new Error('Failed to create playlist');
        const { id: playlistId, external_urls } = await createRes.json() as { id: string; external_urls: { spotify: string } };

        // 5. Add tracks in batches of 100
        for (let i = 0; i < trackUris.length; i += 100) {
            await fetch(`https://api.spotify.com/v1/playlists/${playlistId}/tracks`, {
                method: 'POST',
                headers,
                body: JSON.stringify({ uris: trackUris.slice(i, i + 100) }),
            });
        }

        return NextResponse.json({ playlistUrl: external_urls.spotify, trackCount: trackUris.length });
    } catch (error) {
        console.error('Playlist builder error:', error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}
